db-uri = "postgres://authenticator:authpass@127.0.0.1:54329/ls"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "super-secret-jwt-token-with-at-least-32-characters-long"
server-host = "127.0.0.1"
server-port = 3000
db-pool = 10
log-level = "warn"
